### PR TITLE
Enhance OculusKiller With Integrate OculusSwapper

### PR DESCRIPTION
**Pull request by Eliminater74**
Details:
- **Logging Mechanism**: Introduced a comprehensive logging mechanism to capture the application's flow. Logs are stored in the user's LocalApplicationData directory under "OculusKiller/logs.txt".
- **Graceful Shutdown**: Implemented a graceful shutdown mechanism for the Oculus runtime. The application now attempts to shut down the Oculus process gracefully before forcibly terminating it.
- **Asynchronous Programming**: Integrated asynchronous programming to improve performance. Used `async` and `await` for non-blocking operations, ensuring smoother execution.
- **Retry Mechanism**: Added a retry mechanism for monitoring the `vrserver.exe` process. The application now makes two attempts to detect the process before giving up.
- **Enhanced Monitoring**: Improved the monitoring of `vrserver.exe`. The Oculus process is now terminated only when `vrserver.exe` exits, ensuring synchronization between the two processes.
- **Code Refactoring**: Refactored various parts of the code for better readability, maintainability, and performance. Introduced helper methods and organized the code structure.

This pull request introduces the OculusSwapper, a new feature for the OculusKiller program. The main highlights of this integration are:

OculusDash Swapping: Users can now easily switch between the custom OculusKiller version and the original OculusDash.exe. This provides flexibility for those who want to revert to the original software without much hassle.

System Tray Integration: OculusSwapper runs in the system tray, offering a context menu with various functionalities. This ensures that the features are easily accessible without cluttering the user's desktop or taskbar.

Runtime Process Management: We've added the ability to terminate the OculusDash process directly from the tray menu. Additionally, users can stop and restart various Oculus runtime processes, ensuring that changes take effect immediately without requiring a system restart.

User Feedback: To enhance the user experience, we've incorporated balloon notifications to inform users about the actions they've taken. An 'About' dialog provides information about the software and its usage.

Administrative Privileges Check: The software checks if it's running with the necessary administrative privileges and prompts the user to grant them if not. This ensures smooth operation and minimizes potential issues due to permission restrictions.

By integrating OculusSwapper with OculusKiller, we aim to provide a comprehensive toolset for Oculus users, giving them more control over their software components. We believe this enhancement will greatly benefit the community and look forward to feedback.

### CODE REVIEW

**Comment by Eliminater74** [comment]
I added a simple Tray Menu to allow swapping out beteen OculusKiller and Original OculusDash. The reason for this makes it easier for some users that dont understand how to do it manually or not brave enough to do it manually. also it helps users who wish to sometimes use Oculus Software apps, With the Swapper, they can convert their system on the Fly. 

I am sure there are still some bugs in this, I will work them out as I go along.. Also, if you use this Make sure

the OculusKiller OculusDash.exe is in the same Directory as the OculusSwapper or else it wont work right. a Error box will pop up letting you know this. I also have it in menu to display which one you have installed incase you should forget where you left off at. It will know if its the OculusKiller or the Original OculusDash. and it will display the edition in baloon notify and tray menu.

So this is kinda a Installer, but at the same time allows you to swap out the 2 at any time.

**Comment by noam15A** [comment]
I'm a bit of a noob and have no idea if this is the right place for this. How can I get this OculusSwapper? Is it open for the public or is there intentionally no obvious way to download it? It sounds cool and I want to try it.

**Comment by Eliminater74** [comment]
> I'm a bit of a noob and have no idea if this is the right place for this. How can I get this OculusSwapper? Is it open for the public or is there intentionally no obvious way to download it? It sounds cool and I want to try it.

https://github.com/DevOculus-Meta-Quest/OculusKiller/releases

**Comment by Eliminater74** [comment]
I am going to close this pull request because I feel as the development has pretty much ended or not really of interests to 
the current developers of said project, I have seen pull request that fix many issues but nothing as todays date has been merged to help the many others that would like to see a working copy of this great Program OculusKiller..

But do to that nature I have taken on steps to Just publish my fixes else where for anyone that is interested in latest editions..
with full respect and credits to the Original Author of this said code........... 

https://github.com/DevOculus-Meta-Quest/OculusKiller/releases

**Pull request closed without merging**
